### ISSUE TITLE
4.3 Breaks jest-styled-components

### ISSUE THREAD

**Issue by fabio-b** [rebassjs/grid#128]
Working Versions:
jest-styled-components 5.0.1
**grid-styled 4.2.0** and below
styled-components 3.3.3

Breaking Versions:
jest-styled-components 5.0.1
**grid-styled 4.3.0** and above
styled-components 3.3.3

When running the tests, the dynamic classes that gets substituted out are re-appearing. It also looks like the last class name is repeated. This only affects components that use Flex/Box. Other snapshots from other components continue to work.

Expected:
`className="c0 c1 c2"`
Actual:
`className="c0 c1 c2 sc-bwzfXH c2"`

**Comment by jxnblk** [comment]
The internals of grid-styled shouldn't be affecting your own jest-styled-components tests, right? You shouldn't be testing the output of this library, since it has its own tests

**Comment by fabio-b** [comment]
I agree, however I'm not testing the output of your library specifically. I'm snapshotting my component and it's using yours to render it.
Ex.
```
<Flex>
  <Box><span>Simple box</span></Box>
</Flex>
`

The above example used to produce `classname="c0"`. After 4.3 update it produces `className="c0 sc-bwzfXH c0"`. The only outlier in my dependency package is this library. When I updated every other package except this to the latest, my tests pass and the snapshot files look OK with `c0 c1 ...` classnames. When I upgrade this package only to 4.3 (now 5.0.2), components that use this library in their code break.

The only thing I see that changed in 4.3 was changing over to system-components package. Was there anything else that changed?

**Comment by jxnblk** [comment]
I'm not sure what to do about this issue from this package. I'd suggest trying the latest versions of your dependencies, and perhaps investigating the issue on the styled-components or jest-styled-components repos if you still see the issue
