### ISSUE TITLE
It would be really useful to be able to do offsets of a certain number of columns.

### ISSUE THREAD

**Issue by DylanVann** [rebassjs/grid#134]
I guess that might be more difficult as this grid isn't a fixed number of columns or a fixed gutter width.

Something like:

```jsx
<Box width={1/3} offset={1/3} />
```

**Comment by jxnblk** [comment]
You can use margin (which is how offsets typically work) to do this:

```jsx
<Box width={1/3} ml={100/3 + '%'} />
```

**Comment by DylanVann** [comment]
Yeah, it would be nice to be able to use the same shorthand as for width to do an offset.

**Comment by DylanVann** [comment]
I'll just use a helper for now, but let me know if you want me to submit a PR for adding `offset`.

I've got some crazy stuff going on with offsets... 

```js
const toPercent = (v) => (v * 100) + '%'
```

```js
                width={[1, 1, 5 / 14]}
                ml={[0, 2/14, 1/14].map(toPercent)}
                mr={[0, 2/14, 0].map(toPercent)}
```

**Comment by jxnblk** [comment]
Yeah, you could also wrap what you've got into a component, maybe something like:

```jsx
const Column = ({
  offset = [],
  ...props
}) => 
  <Box {...props} ml={offset.map(toPercent)} />
```

**Comment by DylanVann** [comment]
Hm.. I've been thinking of wrapping them anyways since `Box` doesn't feel as intuitive as `Column` or `Col`. Anyways, thank you so much for the help.

Wether or not you want it as built in functionality is up to you. I do think it's a common use case. Bootstrap has a section of their grid page dedicated to it so that would seem to support that.

**Comment by jxnblk** [comment]
Closing this out since the lower-level margin-based API seems to handle this use-case

**Comment by kbooz** [comment]
> I'll just use a helper for now, but let me know if you want me to submit a PR for adding `offset`.
> 
> I've got some crazy stuff going on with offsets...
> 
> ```js
> const toPercent = (v) => (v * 100) + '%'
> ```
> 
> ```js
>                 width={[1, 1, 5 / 14]}
>                 ml={[0, 2/14, 1/14].map(toPercent)}
>                 mr={[0, 2/14, 0].map(toPercent)}
> ```

I believe this should be highlighted, it was a really good solution and I also implemented it in my project
