### ISSUE TITLE
grid-styled/emotion Flex innerRef causes React warnings and called twice

### ISSUE THREAD

**Issue by istarkov** [rebassjs/grid#135]
grid-styled/emotion Flex innerRef causes React warnings and called twice, second time with ref to itself instead of inner div ref

See example:
https://codesandbox.io/s/o4m144p0w6

Code to reproduce:
```
import { Flex } from "grid-styled/emotion";

export default () =>     
   <Flex p={3} innerRef={r => console.log(r)}>
      Hello
    </Flex>
```

console output:

![image](https://user-images.githubusercontent.com/5077042/43712904-79c126ea-9980-11e8-808b-bbf731898a8a.png)

All is fine if `Box` is used

**Comment by istarkov** [comment]
Also checked same code with styled-components there is an other issue - innerRef provides ref to styled instance instead of ref to `div`

**Comment by jxnblk** [comment]
I've refactored a lot of the code since this was opened. If you still encounter similar problems, please open a new issue
