### ISSUE TITLE
space scales: what is 8px / powers-of-two 

### ISSUE THREAD

**Issue by bochen2014** [rebassjs/grid#142]
the document says
>The default scale is based on an 8px/powers-of-two grid: [ 0, 4, 8, 16, 32, 64, 128, 256, 512 ], which helps keep spacing consistent and elements aligned even when nesting components.

so far I have noticed  m={1} is 8px , m={2} is 16px  m ={3} is 32px;  m={1/2} is 0.5px

where does `4` fit in this pattern??

**Comment by bochen2014** [comment]
isn't powers of two grid be  ` [0,2,4,8,16,32 .... ] `

I don't understand the logic behind the gird mentioned in the document

**Comment by jxnblk** [comment]
Some people refer to it as an "8px grid" – but it's essentially based on powers of two
