### ISSUE TITLE
Styled-components v4 breaks grid-styled 

### ISSUE THREAD

**Issue by marchenko-ia12** [rebassjs/grid#146]
After updating styled-component all props like mb,mt and etc don't work.

**Comment by marco-streng** [comment]
Same here. The props now appear as html attribute on the tag. 

`<div class="sc-bdVaJa jZblEN" px="1,2,3" mb="2">`

**Comment by jxnblk** [comment]
For styled-components v4, you may want to use the new `@rebass/grid` package

**Comment by jxnblk** [comment]
Closing this, but feel free to open a new issue if you still encounter issues with the latest `@rebass/grid` and styled-components v4
