### ISSUE TITLE
What happened to grid-styled?

### ISSUE THREAD

**Issue by hedgerh** [rebassjs/grid#148]
I just joined a project that is using `grid-styled` currently.  I was trying to find documentation for it, and https://github.com/jxnblk/grid-styled redirects here.

Is this a rebranding?  Seems there is a totally different npm package for this grid system, as well.  You may want to add something to the documentation that explains what's going on.  Cheers!

**Comment by jxnblk** [comment]
I've added a note to the readme, for docs for the previous version, you can view the readme at the previous version https://github.com/rebassjs/grid/tree/v5.0.2
