### ISSUE TITLE
width props and values applied to <Box> component are being displayed in DOM

### ISSUE THREAD

**Issue by coreybruyere** [rebassjs/grid#149]
I noticed my DOM is polluted with values I'm passing into `<Flex>` and `<Box>` components within my application leaving me with markup that looks like this:

```
<div class="Hero hUbTkh sc-bdVaJa fXoOjF" order="-1,-1,-1" width="1,1,0.6">...</div>
```

Is this a known thing? If so is there anyway around it to ensure I have valid HTML?

Great library as well!

**Comment by jxnblk** [comment]
See rebassjs/rebass#474 for an explanation of the rational for this change – it boils down to issues with how styled-components whitelists HTML attribute props essentially, and I'm waiting for a solution from the CSS-in-JS libraries. The rendered markup you have above *shouldn't* really cause any issues afaik
