### ISSUE TITLE
Using 'is' on <Box> component doesn't render expected HTML

### ISSUE THREAD

**Issue by coreybruyere** [rebassjs/grid#150]
Using `<Box>` component like so:

```
const FeatureGridListItem = styled(Box)`
  text-align: left;
`;

<FeatureGridListItem
   width={[1, 1, 1 / 2]}
   is="li"
 >
  ...
</FeatureGridListItem>
```

And I'm not receiving any of the expected CSS that I should be receiving from the `<Box>` component

**Comment by jxnblk** [comment]
Thanks, can you list the versions of `@rebass/grid` and `styled-components` that you're using?

**Comment by daveyheuser** [comment]
I'm experiencing the same (the `is` not being passed on). The version displayed in my package.json is `"@rebass/grid": "^6.0.0-0",`.

**Comment by jxnblk** [comment]
This is a change with v6, I've updated the readme to reflect that change here: https://github.com/rebassjs/grid#changing-the-html-element

**Comment by daveyheuser** [comment]
Thanks for the prompt reply, upgrading to styled components v4 fixed it for me!
