### ISSUE TITLE
Box props being passed to underlying dom

### ISSUE THREAD

**Issue by karolisgrinkevicius** [rebassjs/grid#153]
When passing `width` or `order` prop to `Box` component they're being passed to underlying html.

**Dependencies:**
 * styled-components `3.4.9`
 * styled-system `3.1.6`
 * @rebass/grid `6.0.0-3`

**Expected:**
`width` prop is being cleaned from underlying html.

**Screenshot:**
![screen shot 2018-09-24 at 16 03 52](https://user-images.githubusercontent.com/9420403/45953668-80a4dd80-c013-11e8-85eb-6809f7269aa7.png)
![screen shot 2018-09-24 at 16 54 08](https://user-images.githubusercontent.com/9420403/45956152-7f2ae380-c01a-11e8-820c-e392801c1227.png)

**Comment by jxnblk** [comment]
For v6, this is the expected behavior, see https://github.com/rebassjs/rebass/pull/474 for some of the rationale behind this change

**Comment by karolisgrinkevicius** [comment]
@jxnblk is there any proper temporary workaround for removing these props from the DOM?

**Comment by IsenrichO** [comment]
Also wondering about @karolisgrinkevicius's question.
