### ISSUE TITLE
UMD build?

### ISSUE THREAD

**Issue by sgilligan** [rebassjs/grid#156]
Are there any plans to release a umd build of this? I deploy direct to the browser unbundled with SystemJS and can't seem to either create a umd build myself (I'm no rollup/webpack expert), and haven't had any luck with jspm.io.

**Comment by jxnblk** [comment]
Not planning to at the moment. This package is intended to be consumed via npm and with a bundler like webpack. I'd accept a PR as long as it works well with the existing setup

**Comment by sgilligan** [comment]
understood - thanks.
