### ISSUE TITLE
Unmet peer dependency warning for emotion when using styled-components

### ISSUE THREAD

**Issue by lcvbeek** [rebassjs/grid#157]
Sorry if I missed the solution somewhere or if it's a noob question, but is there a way to get rid of this warning? Don't think I had it before, when it was still `grid-styled`.

I'm using `styled-components` as opposed to `emotion`, so I technically don't need it, right?
I take it it'll send `emotion`-users the same warning for `styled-components`? Is there no OR in the peerDependencies?

`" > @rebass/grid@6.0.0-4" has unmet peer dependency "emotion@>=9.0"`
`" > @rebass/grid@6.0.0-4" has unmet peer dependency "react-emotion@>=9.0"`

Thanks!

**Comment by jxnblk** [comment]
I'm not sure if `peerDependencies` supports anything like an *or* operator, but I'd consider removing the `peerDependencies` altogether. That said, the warning shouldn't cause any real issues

**Comment by lcvbeek** [comment]
Thanks for the quick reply. Agreed, it doesn't cause any real issue... just don't want to get used to warnings (or errors of course) that don't require attention. Watching out for warning-blindness. ;)

Still love the library though, by the way. I'll use this as my chance to thank you for all your hard work put into it! 💯

**Comment by thisjeremiah** [comment]
Perhaps “optionalDependencies” would be a good fit here? You wouldn’t get any warnings, but the dependencies would still be documented.
