### ISSUE TITLE
npm WARN @rebass/grid@6.0.0-4 requires a peer of react-emotion@>=9.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by Steffi3rd** [rebassjs/grid#159]
I always have this warning so my webhook netlify failed.

I need just `npm i @rebass/grid`

Why do I have to install `react-emotion` ? How to fix that ? I don't need `react-emotion`, I have `styled-component`

**Comment by jxnblk** [comment]
The peer dependencies should probably be removed altogether
