### ISSUE TITLE
css prop returning undefined properties

### ISSUE THREAD

**Issue by mrseanbaines** [rebassjs/grid#161]
I am running `@rebass/grid` v6.0.0-5 (and have tried other v6.0.0-* versions) and am getting some strange results when using the `css` prop on both `Flex` and `Box` component.

Here is some basic example markup that I've tried:
```js
<Flex justifyContent='center'>
  <Box css={{ height: '100%' }}>
    Some content here...
  </Box>
</Flex>
```

...and I am getting this in my Chrome dev tools:

![image](https://user-images.githubusercontent.com/24367010/49330865-83303000-f58c-11e8-850e-b1d601345a5b.png)

Am I doing something wrong?

**Comment by jxnblk** [comment]
Do you have a theme that you're using along with this? If so, could you include the code for that?

**Comment by mrseanbaines** [comment]
I have a theme being passed down via Styled Components' `ThemeProvider`:

```js
export default {
  fonts: {
    sansSerif:
    '"Barlow", sans-serif',
  },
  colors: {
    main: '#A29BFE',
    mainHover: '#B4AFFF',
    mainSelectedHover: '#ECEBFF',
    white: '#fff',
    black: '#000',
    greys: ['#d7dce0', '#535c68'],
  },
  radii: ['0px', '2px', '4px', '16px', '9999em', '100%'],
};
```

**Comment by kibray** [comment]
@mrseanbaines I had the same issue and I resolved it changing the prop `css` with `style`.

Hope it helps!

**Comment by jxnblk** [comment]
Potentially related: https://github.com/styled-components/babel-plugin-styled-components/issues/186

**Comment by jxnblk** [comment]
This package has moved to https://github.com/rebassjs/rebass/tree/master/packages/reflexbox – if you're still seeing this issue, please open a new issue on that repo
