### ISSUE TITLE
RTL direction support

### ISSUE THREAD

**Issue by gregseed** [rebassjs/grid#164]
Hoping there is an easy answer to this, but is there a way to "reverse" all the ml, mr, pl, pr, etc. for support in switching with languages that read right to left?

**Comment by ahmadalfy** [comment]
If you allow me, you don't need to set anything special except by setting the `dir` attribute of your document to `rtl` and everything will be flipped. This is flexbox at the end it works fine with both directions provided that you supply the correct direction and it will take care of the layout
