### ISSUE TITLE
Problem of layout

### ISSUE THREAD

**Issue by viococo** [rebassjs/grid#165]
Hello !
How can I do something like that ?
![expected](https://user-images.githubusercontent.com/31615012/50149582-e673cf00-02bb-11e9-9772-a9470990b27a.png)

When I try this code, I have a bad result !
```js
<Flex>
  <Box width={1} />
  <Box width={1/2} />
  <Box width={1/2} />
</Flex>
```
the bad result : 
![result](https://user-images.githubusercontent.com/31615012/50149798-6dc14280-02bc-11e9-8192-c37f010adbe1.png)

Thanks

**Comment by jxnblk** [comment]
You'll need `<Flex flexWrap='wrap' />`
