### ISSUE TITLE
Gutters

### ISSUE THREAD

**Issue by FrancisVega** [rebassjs/grid#169]
Is there any way to get real gutters?

Something like:

```
<Flex gutter={3}>
  <Box />
  <Box />
  ...
</Flex>
```

Thanks!

**Comment by storybynumbers** [comment]
The gutters for this system rely on negative margins on the flex container, and padding on the children elements:

```
const gutter = 3;
<Flex mx={-gutter} flexWrap='wrap'>
  <Box px={gutter} />
  <Box px={gutter} />
</Flex>
```

**Comment by jxnblk** [comment]
You can also use `React.Children` to map over the children and add the `px` prop where needed. The props API for Rebass Grid will *not* likely have a `gutter` prop like you've described though

**Comment by FrancisVega** [comment]
Thanks so much!
Congratulations for the work 👏
