### ISSUE TITLE
website is down ATM

### ISSUE THREAD

**Issue by abumalick** [rebassjs/grid#170]
https://rebassjs.org/grid/

https://grid.rebassjs.org/

Just discovered styled system and rebass and it looks really great !

Thanks a lot

**Comment by jxnblk** [comment]
Thanks! Should be back up now at https://grid.rebassjs.org/ – feel free to reopen if you're still seeing issues

**Comment by ashwinv11** [comment]
Still seeing this issue today.. looks like https://grid.rebassjs.org/ isn't pointed to anything?

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;grid.rebassjs.org.		IN	A

;; Query time: 35 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sat Mar 09 14:21:09 PST 2019
;; MSG SIZE  rcvd: 46
```
