### ISSUE TITLE
styled-space > @rebass/space ?

### ISSUE THREAD

**Issue by peteruithoven** [rebassjs/grid#171]
I've been a bit confused by the package name, why isn't the `styled-space` package called `@rebass/space`? Like `@rebass/grid` and `@rebass/components`?

The space is already confusing with `styled-components` and `styled-system`, for me it was clarifying that all the `@rebass/...` where React components.

**Comment by jxnblk** [comment]
Think this was just an oversight. I agree, renaming it to `@rebass/space` seems like a good thing to do

**Comment by jxnblk** [comment]
Renamed here: https://github.com/rebassjs/space
