### ISSUE TITLE
Grid sub domain link no longer valid in repository description.

### ISSUE THREAD

**Issue by grantmoran** [rebassjs/grid#184]
Should be the sub directory [https://rebassjs.org/grid](https://rebassjs.org/grid) link as displayed in the read.me. :)

**Comment by jxnblk** [comment]
Renamed this back to `reflexbox` and moved the URL here https://rebassjs.org/reflexbox/ - will be archiving this repository soon in favor of the https://github.com/rebassjs/rebass monorepo
