### ISSUE TITLE
Passing innerRef to <Box> returns only the styled-component wrapper

### ISSUE THREAD

**Issue by fabio-b** [rebassjs/grid#95]
I'm trying to pass my component's ref to <Box> so that the markup doesn't have 2 dom elements rendered to the page, but the ref that gets returned is the styled-component wrapper.

My component I'm passing in is also a styled-component.

Below is how I'm rendering it - I'm separating innerRef prop to show it being passed.

```
{React.Children.map(children, (child, i) => {
  const { children, innerRef, id, ...props } = child.props;
  return (
    <Box is={child.type} innerRef={innerRef} {...props}>
      {children}
    </Box>
  )
})}
```

If I pass {child} underneath Box, it returns the ref correctly.

**Comment by fabio-b** [comment]
Seems this is related to #44

**Comment by jxnblk** [comment]
I'm guessing that the `innerRef` prop is being passed to you underlying component as the `ref` prop, which will give you the wrapper's refs.

I think adding a check here for whether `is` is a styled component might get around this: https://github.com/jxnblk/styled-system/blob/master/clean-tag/index.js#L31

**Comment by vzaidman** [comment]
worked in ~4.1.0 and ~4.2.0. now bugged indeed

**Comment by autoric** [comment]
Seeing the same - innerRef is broken in 4.3, had to downgrade to 4.2.0

**Comment by jxnblk** [comment]
Thanks! I’m adding some more unit tests for this, feel free to open a new issue if that’s helpful

**Comment by jxnblk** [comment]
Has anyone tested this with v5.0?
